# Generated by Django 3.1.4 on 2021-06-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_arquivo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(blank=True, max_length=150, null=True)),
                ('arquivo', models.FileField(upload_to='static/media')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['id_arquivo'],
                'managed': True,
            },
        ),
    ]
