# Generated by Django 3.1.4 on 2021-06-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='arquivo',
            field=models.FileField(upload_to='core/static/media'),
        ),
    ]
